[package]
name = "aphrodite-slint"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
aphrodite-core = { path = "../aphrodite-core" }
slint = "1.12"

